### ISSUE TITLE
Card Model Error

### ISSUE THREAD

**Issue by akdilsiz** [Chatatata/iyzico#2]
When creating a payment request Iyzico.Card model "register?" parameter is not sent, we get an "Invalid Request" error. Can we make this parameter optional?

**Comment by Chatatata** [comment]
Could you send me a gist about that? As I know, we currently do not use any parameter with name `register?`, but we were in the past.

For your information, if you wish to store a credit card while doing another transaction, you may provide `:registration_alias` field to the card, which is supported but *discouraged*.

**Comment by akdilsiz** [comment]
The problem is solved after I updated to new version. Thank you.
